=== Billy97Proano/aplicaciones_web/practicas_app_webcom/7_XML/agenda.xsd
<?xml version = "1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="Agenda">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="contacto" minOccurs="1"
					maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="contacto" type="contactoTipo" />
	<xsd:complexType name="contactoTipo">
		<xsd:sequence>
			<xsd:element ref="fotografia" />
			<xsd:element ref="titulo" />
			<xsd:element ref="nombre" />
			<xsd:element ref="apellido" />
			<xsd:element ref="paginaWeb" />
			<xsd:element ref="cumpleanios" />
			<xsd:element ref="direccion" />
			<xsd:element ref="empresa" />
			<xsd:element ref="telefono" />
			<xsd:element ref="localizacion" />
			<xsd:element ref="tonos" />
		</xsd:sequence>
		<xsd:attribute ref="id" />
	</xsd:complexType>

	<xsd:element name="empresa">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nombreEmpresa" />
				<xsd:element ref="tipoEmpresa" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="localizacion">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="pais" />
				<xsd:element ref="ciudad" />
				<xsd:element ref="geolocalizacion" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>


	<xsd:element name="tonos">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tonoMensaje" />
				<xsd:element ref="tonoLlamada" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
		<xsd:attribute name="id">
		<xsd:simpleType>
			<xsd:restriction base="xsd:integer">
				<xsd:minInclusive value="1" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
	
	<xsd:element name="fotografia" type="xsd:string" />
	<xsd:element name="titulo" type="xsd:string" />
	<xsd:element name="nombre" type="xsd:string" />
	<xsd:element name="apellido" type="xsd:string" />
	<xsd:element name="paginaWeb" type="xsd:string" />
	<xsd:element name="cumpleanios" type="xsd:string" />
	<xsd:element name="direccion" type="xsd:string" />
	<xsd:element name="nombreEmpresa" type="xsd:string" />
	<xsd:element name="tipoEmpresa" type="xsd:string" />
	<xsd:element name="telefono" type="xsd:string" />
	<xsd:element name="pais" type="xsd:string" />
	<xsd:element name="ciudad" type="xsd:string" />
	<xsd:element name="geolocalizacion" type="xsd:string" />
	<xsd:element name="tonoMensaje" type="xsd:string" />
	<xsd:element name="tonoLlamada" type="xsd:string" />
	

</xsd:schema>

=== Billy97Proano/aplicaciones_web/practicas_app_webcom/7_XML/contactos.xml
<?xml version="1.0" encoding="UTF-8"?>

<Agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="agenda.xsd">

	<contacto id="1">
		<fotografia>www.fotos.com/miFoto.png</fotografia>
		<titulo>Contacto 1</titulo>
		<nombre>Jose</nombre>
		<apellido>Jimenez</apellido>
		<paginaWeb>wwww.josejimenes.com</paginaWeb>
		<cumpleanios>23/07</cumpleanios>
		<direccion>Calderon</direccion>
		<empresa>
			<nombreEmpresa>Claro</nombreEmpresa>
			<tipoEmpresa>Privada</tipoEmpresa>
		</empresa>
		<telefono>0984871823</telefono>		
		<localizacion>
			<pais>Ecuador</pais>
			<ciudad>Quito</ciudad>
			<geolocalizacion>-0.101495,-78.478121</geolocalizacion>
		</localizacion>
		<tonos>
			<tonoMensaje>TonoMensaje1</tonoMensaje>
			<tonoLlamada>TonoLlamada1</tonoLlamada>
		</tonos>
	</contacto>

    <contacto id="2">
		<fotografia>www.fotos.com/miFoto1.png</fotografia>
		<titulo>Contacto 2</titulo>
		<nombre>Cristian</nombre>
		<apellido>Campos</apellido>
		<paginaWeb>wwww.cristiancampos.com</paginaWeb>
		<cumpleanios>01/10</cumpleanios>
		<direccion>Condado</direccion>
		<empresa>
			<nombreEmpresa>Ministerio de Salud Publica</nombreEmpresa>
			<tipoEmpresa>Publica</tipoEmpresa>
		</empresa>
		<telefono>0983333483</telefono>		
		<localizacion>
			<pais>Ecuador</pais>
			<ciudad>Quito</ciudad>
			<geolocalizacion>-0.1021813,-78.5254671</geolocalizacion>
		</localizacion>
		<tonos>
			<tonoMensaje>tonoMensaje2</tonoMensaje>
			<tonoLlamada>tonoLlamada2</tonoLlamada>
		</tonos>
	</contacto>

</Agenda>
